/**
 * Azure DevOps PR creation via az CLI
 */

import { execSync } from 'child_process';
import { log, warn, err } from '../utils/logger.js';
import { summariseText } from '../utils/summariser.js';

const AZ_TIMEOUT = 5 * 60 * 1000;

function escapeArg(arg) {
  if (/[\s"'\\$`!]/.test(arg)) {
    return `"${arg.replace(/["\\$`!]/g, '\\$&')}"`;
  }
  return arg;
}

function buildPRDescription(config, ticketKey, ticketSummary, claudeSummary) {
  return `## Summary
${ticketSummary}

## Implementation Details
${claudeSummary}

## JIRA Ticket
${config.jira.baseUrl}/browse/${ticketKey}

---
*This PR was automatically generated by Dr. Asthana. Please review carefully before merging.*`;
}

/**
 * Create a PR on Azure DevOps
 */
export async function createPR(config, tmpDir, sourceBranch, targetBranch, ticketKey, ticketSummary, claudeSummary) {
  const prefix = `[${ticketKey}] `;
  const maxSummaryChars = Math.max(20, 200 - prefix.length);
  const summarisedTitle = summariseText(ticketSummary || '', {
    preset: 'pr-title',
    label: 'pr-title',
  });
  const title = `${prefix}${summarisedTitle.substring(0, maxSummaryChars)}`;
  const description = buildPRDescription(config, ticketKey, ticketSummary, claudeSummary);

  let repoName = '';
  try {
    const remoteUrl = execSync('git remote get-url origin', {
      cwd: tmpDir, encoding: 'utf-8', stdio: 'pipe',
    }).trim();
    repoName = remoteUrl.split('/').pop().replace('.git', '');
    log(`Detected repo name: ${repoName}`);
  } catch (e) {
    warn(`Could not detect repo name: ${e.message}`);
  }

  const args = [
    'repos', 'pr', 'create',
    '--repository', repoName,
    '--source-branch', sourceBranch,
    '--target-branch', targetBranch,
    '--title', title,
    '--description', description,
    '--draft', 'false',
    '--output', 'json',
  ];

  if (config.azureDevOps.org) {
    args.push('--organization', config.azureDevOps.org);
  }
  if (config.azureDevOps.project) {
    args.push('--project', config.azureDevOps.project);
  }

  log(`Creating PR: ${sourceBranch} -> ${targetBranch}`);

  try {
    const result = execSync(`az ${args.map(escapeArg).join(' ')}`, {
      cwd: tmpDir,
      stdio: 'pipe',
      timeout: AZ_TIMEOUT,
      encoding: 'utf-8',
    });

    const prData = JSON.parse(result);
    const prId = prData.pullRequestId;
    const prUrl = prData.repository?.webUrl
      ? `${prData.repository.webUrl}/pullrequest/${prId}`
      : `PR #${prId}`;

    log(`Created PR #${prId}`);
    return { prId, prUrl };
  } catch (error) {
    const stderr = error.stderr?.toString() || '';
    const stdout = error.stdout?.toString() || '';
    const output = stderr || stdout || error.message;

    if (output.includes('TF401179') || output.includes('already has an active pull request')) {
      log(`PR already exists for branch ${sourceBranch}, looking up existing PR...`);
      return findExistingPR(config, repoName, sourceBranch);
    }

    err(`Failed to create PR: ${output}`);
    return null;
  }
}

function findExistingPR(config, repoName, sourceBranch) {
  try {
    const args = [
      'repos', 'pr', 'list',
      '--repository', repoName,
      '--source-branch', sourceBranch,
      '--status', 'active',
      '--output', 'json',
    ];

    if (config.azureDevOps.org) {
      args.push('--organization', config.azureDevOps.org);
    }
    if (config.azureDevOps.project) {
      args.push('--project', config.azureDevOps.project);
    }

    const result = execSync(`az ${args.map(escapeArg).join(' ')}`, {
      stdio: 'pipe',
      timeout: AZ_TIMEOUT,
      encoding: 'utf-8',
    });

    const prs = JSON.parse(result);
    if (prs.length > 0) {
      const pr = prs[0];
      const prId = pr.pullRequestId;
      const prUrl = pr.repository?.webUrl
        ? `${pr.repository.webUrl}/pullrequest/${prId}`
        : `PR #${prId}`;
      log(`Found existing PR #${prId}`);
      return { prId, prUrl, alreadyExists: true };
    }

    warn(`No active PR found for ${sourceBranch}`);
    return null;
  } catch (e) {
    warn(`Failed to look up existing PR: ${e.message}`);
    return null;
  }
}
