/**
 * Azure DevOps PR creation via az CLI
 */

import { execSync } from 'child_process';
import { log, warn, err } from '../logger.js';
import { summariseText } from './summariser.js';

const AZ_TIMEOUT = 5 * 60 * 1000; // 5 minutes

/**
 * Build PR description
 */
function buildPRDescription(config, ticketKey, ticketSummary, claudeSummary) {
  return `## Summary
${ticketSummary}

## Implementation Details
${claudeSummary}

## JIRA Ticket
${config.JIRA_BASE_URL}/browse/${ticketKey}

---
*This PR was automatically generated by Dr. Asthana. Please review carefully before merging.*`;
}

/**
 * Create a PR on Azure DevOps
 */
export async function createPR(config, tmpDir, sourceBranch, targetBranch, ticketKey, ticketSummary, claudeSummary) {
  const prefix = `[${ticketKey}] `;
  const maxSummaryChars = Math.max(20, 200 - prefix.length);
  const summarisedTitle = summariseText(ticketSummary || '', {
    mode: 'pr-title',
    maxChars: maxSummaryChars,
    style: 'concise',
    extra: 'Keep the actionable technical scope and relevant version identifiers.',
    label: 'pr-title',
  });
  const title = `${prefix}${summarisedTitle}`;
  const description = buildPRDescription(config, ticketKey, ticketSummary, claudeSummary);

  // Extract repo name from the git remote in tmpDir
  let repoName = '';
  try {
    const remoteUrl = execSync('git remote get-url origin', {
      cwd: tmpDir, encoding: 'utf-8', stdio: 'pipe',
    }).trim();
    // Extract repo name from the last segment of the remote URL
    repoName = remoteUrl.split('/').pop().replace('.git', '');
    log(`Detected repo name: ${repoName}`);
  } catch (e) {
    warn(`Could not detect repo name from git remote: ${e.message}`);
  }

  // Build az command arguments
  const args = [
    'repos', 'pr', 'create',
    '--repository', repoName,
    '--source-branch', sourceBranch,
    '--target-branch', targetBranch,
    '--title', title,
    '--description', description,
    '--draft', 'false',
    '--output', 'json',
  ];

  // Add org/project
  if (config.AZDO_ORG) {
    args.push('--organization', config.AZDO_ORG);
  }
  if (config.AZDO_PROJECT) {
    args.push('--project', config.AZDO_PROJECT);
  }

  log(`Creating PR: ${sourceBranch} → ${targetBranch}`);

  try {
    // Use array-based execution to avoid shell escaping issues
    const result = execSync(`az ${args.map(escapeArg).join(' ')}`, {
      cwd: tmpDir,
      stdio: 'pipe',
      timeout: AZ_TIMEOUT,
      encoding: 'utf-8',
    });

    const prData = JSON.parse(result);
    const prId = prData.pullRequestId;
    const prUrl = prData.repository?.webUrl
      ? `${prData.repository.webUrl}/pullrequest/${prId}`
      : `PR #${prId}`;

    log(`Created PR #${prId}`);
    return { prId, prUrl };
  } catch (error) {
    const stderr = error.stderr?.toString() || '';
    const stdout = error.stdout?.toString() || '';
    const output = stderr || stdout || error.message;

    // Check for "PR already exists" error (TF401179)
    if (output.includes('TF401179') || output.includes('already has an active pull request')) {
      log(`PR already exists for branch ${sourceBranch}, looking up existing PR...`);
      return findExistingPR(config, repoName, sourceBranch);
    }

    err(`Failed to create PR: ${output}`);
    return null;
  }
}

/**
 * Look up an existing active PR for a source branch.
 * Returns { prId, prUrl, alreadyExists: true } or null if not found.
 */
function findExistingPR(config, repoName, sourceBranch) {
  try {
    const args = [
      'repos', 'pr', 'list',
      '--repository', repoName,
      '--source-branch', sourceBranch,
      '--status', 'active',
      '--output', 'json',
    ];

    if (config.AZDO_ORG) {
      args.push('--organization', config.AZDO_ORG);
    }
    if (config.AZDO_PROJECT) {
      args.push('--project', config.AZDO_PROJECT);
    }

    const result = execSync(`az ${args.map(escapeArg).join(' ')}`, {
      stdio: 'pipe',
      timeout: AZ_TIMEOUT,
      encoding: 'utf-8',
    });

    const prs = JSON.parse(result);
    if (prs.length > 0) {
      const pr = prs[0];
      const prId = pr.pullRequestId;
      const prUrl = pr.repository?.webUrl
        ? `${pr.repository.webUrl}/pullrequest/${prId}`
        : `PR #${prId}`;
      log(`Found existing PR #${prId}`);
      return { prId, prUrl, alreadyExists: true };
    }

    warn(`No active PR found for ${sourceBranch}`);
    return null;
  } catch (e) {
    warn(`Failed to look up existing PR: ${e.message}`);
    return null;
  }
}

/**
 * Escape a shell argument
 */
function escapeArg(arg) {
  // If arg contains special characters, wrap in quotes and escape internal quotes
  if (/[\s"'\\$`!]/.test(arg)) {
    return `"${arg.replace(/["\\$`!]/g, '\\$&')}"`;
  }
  return arg;
}

export default { createPR };
