export const STEPS = {
  FETCH_TICKET: 'FETCH_TICKET',
  VALIDATE_TICKET: 'VALIDATE_TICKET',
  CLONE_REPO: 'CLONE_REPO',
  EXECUTE: 'EXECUTE',
  DIFF_REVIEW: 'DIFF_REVIEW',
  SHIP: 'SHIP',
  NOTIFY: 'NOTIFY',
};
